- libs/jwst-storage/src/docs/storage.rs
Used in client app to store whole yjs state.
> feat: pub some doc storage methods

- apps/frontend/libs/jwt/src/block/abstract.ts
> fix: disable cache after modify yBlock children

- Cargo.lock
- libs/jwst-logger/src/formatter.rs
> feat: dont print colors in server side

- Cargo.lock
- apps/cloud/src/main.rs
- apps/keck/src/main.rs
- libs/jwst-logger/Cargo.toml
- libs/jwst-logger/build.rs
- libs/jwst-logger/src/lib.rs
> feat: add runtime version log

- apps/keck/src/server/api/blocks/block.rs
- apps/keck/src/server/api/blocks/mod.rs
- apps/keck/src/server/api/blocks/workspace.rs
- libs/jwst/src/workspaces/transaction.rs
> feat: provide api for searching and createing block by flavor 

- Cargo.lock
- Cargo.toml
- apps/cloud/src/api/ws.rs
- apps/cloud/src/context.rs
- apps/keck/src/server/api/mod.rs
- apps/keck/src/server/sync/collaboration.rs
- libs/jwst-rpc/Cargo.toml
- libs/jwst-rpc/src/broadcast.rs
- libs/jwst-rpc/src/client.rs
- libs/jwst-rpc/src/connector.rs
- libs/jwst-rpc/src/context.rs
- libs/jwst-rpc/src/lib.rs
- libs/jwst/src/workspaces/mod.rs
- libs/jwst/src/workspaces/workspace.rs
- apply update performance optimie
- split socket process logic
- transport impl independent data sync logic
- split some data logic to trait
> feat: rpc optimize

- README.md
- apps/handbook/src/SUMMARY.md
- apps/handbook/src/core_concept.md
- apps/handbook/src/how_to_organize_your_data.md
- apps/handbook/src/quick_start.md
- apps/handbook/src/tour_api.md
- apps/handbook/src/use_case.md
> docs: update keyword

- apps/cloud/src/context.rs
- libs/jwst-storage/src/storage/docs/database.rs
> feat: use memory db if not provide db url

- .github/workflows/jwst.yml
- Cargo.lock
- apps/cloud/Cargo.toml
- apps/cloud/src/context.rs
- libs/jwst-rpc/src/broadcast.rs
- libs/jwst-rpc/src/context.rs
- libs/jwst-rpc/src/lib.rs
- libs/jwst-storage/src/storage/docs/database.rs
- libs/jwst-storage/src/storage/mod.rs
- libs/jwst-storage/src/storage/test.rs
- fix storage lock in server start without database url cc @Himself65 
- only insert changed updates when the connection is not disconnected to optimize storage performance fix #284
> feat: storage optimize

- apps/keck/src/server/api/blobs.rs
- apps/keck/src/server/api/blocks/block.rs
- apps/keck/src/server/api/blocks/mod.rs
- apps/keck/src/server/api/blocks/workspace.rs
> feat: assign flavor when creating block

- apps/keck/src/server/api/blocks/schema.rs
- libs/jwst/src/block.rs
- libs/jwst/src/space/mod.rs
- libs/jwst/src/workspaces/workspace.rs
close #291 
```json
{
"sys:children": [],
"sys:created": 1679473264652.0,
"sys:flavor": "list",
"sys:version": [
1.0,
0.0
]
}
```
```json
{
"sys:id": "0",
"sys:children": [],
"sys:created": 1679473264652.0,
"sys:flavor": "list",
"sys:version": [
1.0,
0.0
]
}
```
> feat: add block_id for serialized block

- apps/cloud/src/api/workspace.rs
> fix: replace get_permission with can_read_workspace 

- apps/cloud/src/files.rs
- apps/cloud/src/layer.rs
- apps/cloud/src/main.rs
- libs/jwst-rpc/src/lib.rs
> chore: cleanup logs

- apps/android/app/src/main/java/com/example/jwst_demo/MainActivity.kt
- libs/jwst-binding/jwst-jni/android/src/main/java/com/toeverything/jwst/JWST.kt
- libs/jwst-binding/jwst-jni/android/src/main/java/com/toeverything/jwst/lib/Workspace.java
- libs/jwst-binding/jwst-jni/src/java_glue.rs.in
- libs/jwst-binding/jwst-jni/src/storage.rs
- libs/jwst-binding/jwst-jni/src/workspace.rs
> feat: add getBlocksByFlavour binding for android

- apps/cloud/src/api/blobs.rs
- apps/cloud/src/api/permissions.rs
- apps/cloud/src/api/workspace.rs
> chore: complete test cases for affine-cloud

- apps/android/app/src/main/java/com/example/jwst_demo/MainActivity.kt
- libs/jwst-binding/jwst-jni/android/src/main/java/com/toeverything/jwst/JWST.kt
- libs/jwst-binding/jwst-jni/android/src/main/java/com/toeverything/jwst/lib/JwstStorage.java
- libs/jwst-binding/jwst-jni/build.rs
- libs/jwst-binding/jwst-jni/src/java_glue.rs.in
- libs/jwst-binding/jwst-jni/src/storage.rs
> feat: add log level control for jni

- Cargo.lock
- libs/jwst-binding/jwst-swift/Cargo.toml
- libs/jwst-binding/jwst-swift/src/lib.rs
- libs/jwst-binding/jwst-swift/src/storage.rs
- libs/jwst-logger/src/lib.rs
- libs/jwst-logger/src/logger.rs
> feat: add log level control for swift-binding

- apps/cloud/src/context.rs
Related to: https://github.com/toeverything/OctoBase/pull/336#discussion_r1153967499
> fix: save tempdir instance and automatically delete the directory when the program exits

- .env-template
- apps/cloud/src/main.rs
- apps/keck/src/main.rs
- apps/keck/src/server/api/blocks/block.rs
- libs/jwst-logger/src/logger.rs
Related to: https://github.com/toeverything/OctoBase/pull/350#issuecomment-1494940037
/cc @Himself65
> fix: unable to start when missing env file

- libs/jwst-rpc/src/broadcast.rs
- libs/jwst/src/workspaces/observe.rs
- libs/jwst/src/workspaces/workspace.rs
> fix: awareness subscription memory leak

- .github/CLA.md
- Cargo.lock
- libs/jwst-rpc/Cargo.toml
- libs/jwst-rpc/src/connector/mod.rs
- libs/jwst-rpc/src/connector/webrtc.rs
- libs/jwst-rpc/src/handler.rs
- libs/jwst-rpc/src/lib.rs
> feat: add webrtc connector

- .github/CLA.md
- libs/jwst-storage/src/storage/blobs/bucket_local_db.rs
This PR will implement BucketBlobStorage for BucketStorage. And I will continue the work of `impl BlobStorage for BlobBucketDBStorage` in next PR.
Part of https://github.com/toeverything/OctoBase/issues/464
`delete_blob` returns `Result<bool>`. However, opendal will always return success if file is not exist. Do we need to check file first before delete it?
> feat: Implement BucketBlobStorage for BucketStorage

- .github/workflows/jwst.yml
- Cargo.lock
- libs/jwst-codec/Cargo.toml
- libs/jwst-codec/fuzz/Cargo.lock
- libs/jwst-codec/src/codec/buffer.rs
- libs/jwst-codec/src/doc/awareness.rs
- libs/jwst-codec/src/doc/codec/any.rs
- libs/jwst-codec/src/doc/codec/content.rs
- libs/jwst-codec/src/doc/codec/item.rs
- libs/jwst-codec/src/doc/codec/refs.rs
- libs/jwst-codec/src/doc/codec/update.rs
- libs/jwst-codec/src/doc/codec/utils/items.rs
- libs/jwst-codec/src/doc/document.rs
- libs/jwst-codec/src/doc/mod.rs
- libs/jwst-codec/src/doc/store.rs
- libs/jwst-codec/src/doc/types/array.rs
- libs/jwst-codec/src/doc/types/list/search_marker.rs
- libs/jwst-codec/src/doc/types/map.rs
- libs/jwst-codec/src/doc/types/mod.rs
- libs/jwst-codec/src/doc/types/text.rs
- libs/jwst-codec/src/lib.rs
- libs/jwst-codec/src/protocol/scanner.rs
- libs/jwst-codec/src/sync.rs
> feat: add loom to test multi-thread ops

- libs/jwst-codec/Cargo.toml
- libs/jwst-codec/src/doc/codec/any.rs
- libs/jwst-codec/src/doc/codec/content.rs
- libs/jwst-codec/src/doc/codec/delete_set.rs
- libs/jwst-codec/src/doc/codec/item.rs
- libs/jwst-codec/src/doc/codec/mod.rs
- libs/jwst-codec/src/doc/codec/refs.rs
- libs/jwst-codec/src/doc/codec/update.rs
- libs/jwst-codec/src/doc/codec/utils/items.rs
- libs/jwst-codec/src/doc/codec/utils/mod.rs
- libs/jwst-codec/src/doc/common/mod.rs
- libs/jwst-codec/src/doc/common/somr.rs
- libs/jwst-codec/src/doc/document.rs
- libs/jwst-codec/src/doc/mod.rs
- libs/jwst-codec/src/doc/store.rs
- libs/jwst-codec/src/doc/types/array.rs
- libs/jwst-codec/src/doc/types/list/iterator.rs
- libs/jwst-codec/src/doc/types/list/mod.rs
- libs/jwst-codec/src/doc/types/list/search_marker.rs
- libs/jwst-codec/src/doc/types/map.rs
- libs/jwst-codec/src/doc/types/mod.rs
- libs/jwst-codec/src/doc/types/text.rs
- libs/jwst-codec/src/lib.rs
- libs/jwst-codec/src/sync.rs
replace `Arc` with `Somr` (Single owner multiple references lazily dropped head data type)
> refacting: crdt items refs optimize

- libs/jwst-binding/jwst-jni/android/build.gradle
- libs/jwst-storage/src/storage/docs/utils.rs
temporarily disable gc due to multiple client logic
> chore: disable gc
